version: '3'

services:
  lb:
    image: haproxy
    ports:
      - "8085:8085"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy

  soloq1:
    image: soloq
    environment: 
      - DEDICATED_PORT=3005

  soloq2:
    image: soloq
    environment: 
      - DEDICATED_PORT=3006

  soloq3:
    image: soloq
    environment: 
      - DEDICATED_PORT=3007